name: CI

on:
  push:
    branches:
      - master
    tags:
      - 'v[0-9]+.[0-9]+'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: ppnf_devel
          environment-file: ppnf_devel.yml
          auto-update-conda: true
          channels: conda-forge
          channel-priority: strict
          auto-activate-base: false
      - name: Build and test C++ code
        shell: bash -el {0}
        run: |
          mkdir build_cpp && cd build_cpp
          cmake ../ -G "Ninja" \
            -DCMAKE_PREFIX_PATH=$CONDA_PREFIX \
            -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX \
            -DCMAKE_BUILD_TYPE=Release \
            -DPPNF_BUILD_CPP=yes \
            -DPPNF_BUILD_TESTS=yes \
            -DPPNF_BUILD_PYTHON=no
          cmake --build . --target install -j4
          ctest -j4 -V --output-on-failure
      - name: Build and test Python bindings
        shell: bash -el {0}
        run: |
          mkdir build_py && cd build_py
          cmake ../ -G "Ninja" \
            -DCMAKE_PREFIX_PATH=$CONDA_PREFIX \
            -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX \
            -DCMAKE_BUILD_TYPE=Release \
            -DPPNF_BUILD_CPP=no \
            -DPPNF_BUILD_PYTHON=yes
          cmake --build . --target install -j4
          cd ~
          python -c "import pygmo_plugins_nonfree; import pygmo; pygmo_plugins_nonfree.test.run_test_suite(1); pygmo.mp_bfe.shutdown_pool()"

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: ppnf_devel
          environment-file: ppnf_devel.yml
          auto-update-conda: true
          channels: conda-forge
          channel-priority: strict
          auto-activate-base: false
      - name: Build and test C++ code
        shell: bash -el {0}
        run: |
          mkdir build_cpp && cd build_cpp
          cmake ../ -G "Ninja" \
            -DCMAKE_PREFIX_PATH=$CONDA_PREFIX \
            -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX \
            -DCMAKE_BUILD_TYPE=Release \
            -DPPNF_BUILD_CPP=yes \
            -DPPNF_BUILD_TESTS=yes \
            -DPPNF_BUILD_PYTHON=no
          cmake --build . --target install -j4
          ctest -j4 -V --output-on-failure
      - name: Build and test Python bindings
        shell: bash -el {0}
        run: |
          mkdir build_py && cd build_py
          cmake ../ -G "Ninja" \
            -DCMAKE_PREFIX_PATH=$CONDA_PREFIX \
            -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX \
            -DCMAKE_BUILD_TYPE=Release \
            -DPPNF_BUILD_CPP=no \
            -DPPNF_BUILD_PYTHON=yes
          cmake --build . --target install -j4
          cd ~
          python -c "import pygmo_plugins_nonfree; import pygmo; pygmo_plugins_nonfree.test.run_test_suite(1); pygmo.mp_bfe.shutdown_pool()"

  windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: ppnf_devel
          environment-file: ppnf_devel.yml
          auto-update-conda: true
          channels: conda-forge
          channel-priority: strict
          auto-activate-base: false
      - name: Build and test C++ code
        shell: pwsh
        run: |
          mkdir build_cpp
          cd build_cpp
          cmake ../ -G "Visual Studio 17 2022" -A x64 `
            -DCMAKE_PREFIX_PATH="$env:CONDA_PREFIX" `
            -DCMAKE_INSTALL_PREFIX="$env:CONDA_PREFIX" `
            -DPPNF_BUILD_CPP=yes `
            -DPPNF_BUILD_TESTS=yes `
            -DPPNF_BUILD_PYTHON=no
          cmake --build . -j4 --config Release --target install
          cp tests\Release\snopt7_c.dll tests\
          cp tests\Release\worhp_c.dll tests\
          ctest -j4 -V -C Release --output-on-failure
      - name: Build and test Python bindings
        shell: pwsh
        run: |
          mkdir build_py
          cd build_py
          cmake ../ -G "Visual Studio 17 2022" -A x64 `
            -DCMAKE_PREFIX_PATH="$env:CONDA_PREFIX" `
            -DCMAKE_INSTALL_PREFIX="$env:CONDA_PREFIX\Library" `
            -DPPNF_BUILD_PYTHON=yes `
            -DPPNF_BUILD_CPP=no
          cmake --build . -j4 --config Release --target install
          cd $env:TEMP
          python -c "import pygmo_plugins_nonfree; import pygmo; pygmo_plugins_nonfree.test.run_test_suite(1); pygmo.mp_bfe.shutdown_pool()"
